[app]
server_port = 4000

[database]
database_url = "postgres://myuser:mypassword@localhost:5432/mydatabase"

[jwt]
jwt_secret = "secret"
jwt_access_secret = "access_secret"
jwt_refresh_secret = "refresh_secret"
jwt_access_time = 60 # 1 * 60
jwt_refresh_time = 86400 # 1 * 60 * 

[smtp]
smtp_from = "???"
smtp_user_name = "???"
smtp_password = "???"

[oauth2]
oauth2_google_client_id = "???"
oauth2_google_client_secret = "???"