[app]
server_protocol = "http"
server_host = "localhost"
server_port = 4000
csrf_key = "csrf_csrf_csrf_csrf_csrf_csrf_csrf_csrf_csrf_csrf_csrf_csrf_csrf"

[database]
database_url = "postgres://myuser:mypassword@localhost/mydatabase"

[redis]
redis_url = "redis://localhost"

[jwt]
jwt_access_secret = "access_access_access_access_access_access_access_access_access_access"
jwt_refresh_secret = "refresh_refresh_refresh_refresh_refresh_refresh_refresh_refresh_refresh"
jwt_access_time = 60 # 1 * 60
jwt_refresh_time = 86400 # 1 * 60 * 

[smtp]
smtp_from = "???"
smtp_user_name = "???"
smtp_password = "???"

[oauth2]
oauth2_google_client_id = "???"
oauth2_google_client_secret = "???"