database_url = "postgres://myuser:mypassword@localhost:5432/mydatabase"
server_port = 4000
jwt_secret = "secret"
jwt_access_secret = "access_secret"
jwt_refresh_secret = "refresh_secret"
smtp_from = ""
smtp_user_name = ""
smtp_password = ""